import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.scss";
import NoteCard from "@/components/NoteCard";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const notes = useSelector(state => state.notes.initialNotes)
  const router = useRouter()


  return (
    <>
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={`${styles.h1} `}>Welcome To Notes</h1>

        <button
        onClick={()=> router.push('/create')}
        >Create One</button>

        {
          notes?.map((note, index) =>
            
              <NoteCard key={index} note={note} />
            
            )
        }

        

      </main>
    </>
  );
}
